import "./globals.css"
import NavBarCompPage from "./(components)/_navbarcomp/page"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="p-0 m-0 box-border">
        <NavBarCompPage />
        {children}
        <footer className="bg-slate-600 h-24">
          <div className="flex flex-col flex-wrap h-full font-bold text-slate-200 p-4 cursor-pointer text-lg">
            <div>VERA Fundamentals</div>
            <div>Partners For Advancement</div>
            <div>Portfolio Editor</div>
            <div>Contant-us</div>
          </div>
        </footer>
      </body>
    </html>
  )
}
